autoscaling:
  enabled: true
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 60
    type: Resource
  minReplicas: 1
configmap:
  data:
    MESSAGE: hello world
    VERSION: v0.6.10
  enabled: true
datadog:
  enabled: true
  env: alpha
env:
- name: PROFILE
  value: dev
# - name: DD_AGENT_ENABLED
#   value: 'true'
- name: ENV_HASH
  value: bb2af5df59f1a520be1599fde3d09a1e
image:
  repository: nalbam/sample-node
  tag: v0.6.10
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  enabled: true
  hosts:
  - host: sample-node.alpha.jp.karrotmarket.com
    paths:
    - /
secret:
  data:
    SECRET_MESSAGE: c2VjcmV0IG1lc3NhZ2U=
    SECRET_VERSION: djAuNi4xMA==
  enabled: true
