autoscaling:
  enabled: true
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 60
    type: Resource
  minReplicas: 1
controller:
  kind: Rollout
configmap:
  data:
    MESSAGE: hello world
    VERSION: v0.6.9
  enabled: true
datadog:
  enabled: true
  env: alpha
env:
- name: PROFILE
  value: dev
- name: DD_AGENT_ENABLED
  value: 'true'
- name: ENV_HASH
  value: 1d899ebd6eecbdbe21ee6818ae707282
image:
  repository: nalbam/sample-node
  tag: v0.6.9
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  enabled: true
  hosts:
  - host: sample-node.alpha.kr.karrotmarket.com
    paths:
    - /
  - host: sample-node.alpha-a.kr.karrotmarket.com
    paths:
    - /
  - host: sample-node.alpha-b.kr.karrotmarket.com
    paths:
    - /
secret:
  data:
    SECRET_MESSAGE: c2VjcmV0IG1lc3NhZ2U=
    SECRET_VERSION: djAuNi45
  enabled: true
strategy:
  canary:
    canaryService: sample-node-preview
    steps:
    - setWeight: 25
    - analysis:
        templateName: sample-node-http-benchmark
    - setWeight: 50
    - pause:
        duration: 10
    - setWeight: 75
    - pause:
        duration: 10
analysis:
  enabled: true
  url: http://sample-node-preview:3000/success/98
preview:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  enabled: true
  hosts:
  - host: sample-node-preview.alpha.kr.karrotmarket.com
    paths:
    - /
  - host: sample-node-preview.alpha-a.kr.karrotmarket.com
    paths:
    - /
  - host: sample-node-preview.alpha-b.kr.karrotmarket.com
    paths:
    - /
