autoscaling:
  enabled: true
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 60
    type: Resource
  minReplicas: 1
configmap:
  data:
    MESSAGE: hello world
    VERSION: v0.6.20
  enabled: true
datadog:
  enabled: true
  env: alpha
env:
- name: PROFILE
  value: dev
- name: DD_AGENT_ENABLED
  value: 'true'
- name: ENV_HASH
  value: 28682f7e557e6638b1d7a87d5d935d09
image:
  repository: nalbam/sample-spring
  tag: v0.6.20
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  enabled: true
  hosts:
  - host: sample-spring.alpha.kr.karrotmarket.com
    paths:
    - /
  - host: sample-spring.alpha-a.kr.karrotmarket.com
    paths:
    - /
  - host: sample-spring.alpha-b.kr.karrotmarket.com
    paths:
    - /
secret:
  data:
    SECRET_MESSAGE: c2VjcmV0IG1lc3NhZ2U=
    SECRET_VERSION: djAuNi4yMA==
  enabled: true
serviceMonitor:
  enabled: false
