autoscaling:
  enabled: true
  maxReplicas: 5
  metrics:
  - pods:
      metricName: container_network_receive_bytes
      targetAverageValue: 10k
    type: Pods
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 2
configmap:
  data:
    MESSAGE: hello world
    VERSION: v0.6.18
  enabled: true
controller:
  kind: Rollout
datadog:
  enabled: true
  env: alpha
env:
- name: PROFILE
  value: dev
- name: DD_AGENT_ENABLED
  value: 'true'
- name: ENV_HASH
  value: 49c0a28bb85ce64c3bef165ec476f1b5
image:
  repository: nalbam/sample-spring
  tag: v0.6.18
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: 'true'
  enabled: true
  hosts:
  - host: sample-spring-dev.bruce.spic.me
    paths:
    - /
preview:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ssl-redirect: 'true'
  enabled: true
  hosts:
  - host: sample-spring-dev-preview.bruce.spic.me
    paths:
    - /
secret:
  data:
    SECRET_MESSAGE: c2VjcmV0IG1lc3NhZ2U=
    SECRET_VERSION: djAuNi4xOA==
  enabled: true
strategy:
  blueGreen:
    activeService: sample-spring
    autoPromotionEnabled: true
    autoPromotionSeconds: 30
    previewService: sample-spring-preview
